server:
  port: 10086
  servlet:
    context-path: /examsweb
  tomcat:
    max-http-post-size: 0
    accesslog:
      enabled: true
      rotate: true
      file-date-format: yyyy-MM-dd
      request-attributes-enabled: false
      rename-on-rotate: false
      prefix: access-log-
      buffered: true
      pattern: "%h %l %T %t %r %s %b %{Referer}i %{User-Agent}i (%D ms)"
      suffix: .log
      directory: /logs/exams
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB
  freemarker:
    suffix: .html
    request-context-attribute: request
    content-type: text/html
    cache: false
    charset: UTF-8
  datasource:
    name: dataSource1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/examsdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ghzx@7519
    type: com.alibaba.druid.pool.DruidDataSource
    #druid属性
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  redis:
    host: 127.0.0.1
    #password: ghzx7519
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
  cache:
    redis:
      key-prefix: true
      time-to-live: 3m
logging:
  level:
    root: info
    #cn.unicom.exams.service.mapper：debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: 9001

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: cn.unicom.exams.model.entity

exams:
  passNum: 60
