server:
  port: 10086
  servlet:
    context-path: /examsweb
  tomcat:
    max-http-post-size: 0
    accesslog:
      enabled: true
      rotate: true
      file-date-format: yyyy-MM-dd
      request-attributes-enabled: false
      rename-on-rotate: false
      prefix: access-log-
      buffered: true
      pattern: "%{X-Forwarded-For}i %h %l %T %t %r %s %b  %{User-Agent}i (%D ms)"
      suffix: .log
      directory: /usr/local/examsweb/logs/accesslogs/
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB
  freemarker:
    suffix: .html
    request-context-attribute: request
    content-type: text/html
    cache: false
    charset: UTF-8
  datasource:
    name: dataSource1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/examsdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: ghzx@7519
    type: com.alibaba.druid.pool.DruidDataSource
    #druid属性
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
logging:
  level:
    root: info
    #cn.unicom.exams.service: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: 10087

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: cn.unicom.exams.model.entity

exams:
  passNum: 60
  key: 1234567890abcdef
  uploadPath: d:/opt/examsweb/
  resourceWeb: http://127.0.0.1:8786
  ALLOWED_SERVERNAMES: 127.0.0.1,20.1.198.11,20.1.198.12
  ACCESS_MANAGER_SERVERNAMES: 127.0.0.1,20.1.198.0,202.106.86.0
